sudo: false

os:
- linux

git:
  depth: 200

env:
  global:
    - BINSTAR_USER: menpo
  matrix:
    - PYTHON_VERSION: 2.7

addons:
 apt:
   sources:
   - ubuntu-toolchain-r-test
   packages:
   - gcc-4.8
   - g++-4.8

install:
- wget https://raw.githubusercontent.com/menpo/condaci/v0.4.8/condaci.py -O condaci.py
- python condaci.py setup
# Required for llvmdev (static)
- ~/miniconda/bin/conda config --add channels http://conda.binstar.org/numba

script:
- export CXX="g++-4.8" CC="gcc-4.8"
- ~/miniconda/bin/python condaci.py build ./conda

notifications:
  slack:
    rooms:
      - menpo:19gyWImMkOfCj0iDAgTbDlDA
    on_success: :change
    on_failure: :change
  email: false
