package:
  name: osmesa
  version: "12.2.2.dev"

source:
  fn: mesa-12.2.2.dev.zip
  url: https://github.com/menpo/mesa/archive/expose_attrib.zip

requirements:
  build:
    - python
    - mako
    - llvmdev

test:
  commands:
    - test -f $PREFIX/lib/libOSMesa.dylib  # [osx]
    - test -f $PREFIX/lib/libOSMesa.so     # [linux]

about:
  home: http://www.mesa3d.org/
  license: MIT + Others
